/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityTimeline: typeof import('./src/components/incidents/ActivityTimeline.vue')['default']
    AgentActivityPanel: typeof import('./src/components/incidents/AgentActivityPanel.vue')['default']
    AgentConversation: typeof import('./src/components/agent/AgentConversation.vue')['default']
    AgentHistory: typeof import('./src/components/agent/AgentHistory.vue')['default']
    AgentInspector: typeof import('./src/components/agent/AgentInspector.vue')['default']
    AlertBadges: typeof import('./src/components/alerts/AlertBadges.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    ApprovalPanel: typeof import('./src/components/incidents/ApprovalPanel.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AttentionFlag: typeof import('./src/components/incidents/AttentionFlag.vue')['default']
    CodeDiff: typeof import('./src/components/incidents/CodeDiff.vue')['default']
    CommandFeedback: typeof import('./src/components/incidents/CommandFeedback.vue')['default']
    DeliveryRail: typeof import('./src/components/incidents/DeliveryRail.vue')['default']
    EvidenceTable: typeof import('./src/components/incidents/EvidenceTable.vue')['default']
    GlobalAgentPanel: typeof import('./src/components/agent/GlobalAgentPanel.vue')['default']
    HashValue: typeof import('./src/components/incidents/HashValue.vue')['default']
    IncidentFilterBar: typeof import('./src/components/incidents/IncidentFilterBar.vue')['default']
    IncidentHeader: typeof import('./src/components/incidents/IncidentHeader.vue')['default']
    IncidentSectionShell: typeof import('./src/components/incidents/IncidentSectionShell.vue')['default']
    IncidentSignalStrip: typeof import('./src/components/incidents/IncidentSignalStrip.vue')['default']
    IncidentStatusBadge: typeof import('./src/components/incidents/IncidentStatusBadge.vue')['default']
    IncidentTable: typeof import('./src/components/incidents/IncidentTable.vue')['default']
    JSONSnapshot: typeof import('./src/components/incidents/JSONSnapshot.vue')['default']
    MobileBottomNav: typeof import('./src/components/layout/MobileBottomNav.vue')['default']
    NotificationInbox: typeof import('./src/components/layout/NotificationInbox.vue')['default']
    OperationsAtlas: typeof import('./src/components/infrastructure/OperationsAtlas.vue')['default']
    PersistedContextPanel: typeof import('./src/components/incidents/PersistedContextPanel.vue')['default']
    RemediationWorkbench: typeof import('./src/components/incidents/RemediationWorkbench.vue')['default']
    ResolutionReport: typeof import('./src/components/incidents/ResolutionReport.vue')['default']
    ResultBadge: typeof import('./src/components/incidents/ResultBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeverityBadge: typeof import('./src/components/incidents/SeverityBadge.vue')['default']
    SidebarMenu: typeof import('./src/components/layout/SidebarMenu.vue')['default']
    StateBlock: typeof import('./src/components/incidents/StateBlock.vue')['default']
    StructuredResourceView: typeof import('./src/components/infrastructure/StructuredResourceView.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    VerificationMatrix: typeof import('./src/components/incidents/VerificationMatrix.vue')['default']
    ZoneNav: typeof import('./src/components/incidents/ZoneNav.vue')['default']
  }
}
