{{- if .Values.observability.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.observability.elastic.elasticsearch.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudops-kind-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: logs
spec:
  version: {{ .Values.observability.elastic.version | quote }}
  image: {{ include "cloudops-kind-platform.image" .Values.observability.elastic.elasticsearch.image | quote }}
  auth:
    roles:
      - secretName: {{ .Values.observability.elastic.elasticsearch.readRoleSecretName | quote }}
  http:
    service:
      spec:
        type: ClusterIP
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          automountServiceAccountToken: false
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: {{ .Values.observability.elastic.elasticsearch.javaOpts | quote }}
              resources:
                {{- toYaml .Values.observability.elastic.elasticsearch.resources | nindent 16 }}
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: {{ .Values.observability.elastic.elasticsearch.storage.size | quote }}
            {{- if .Values.observability.elastic.elasticsearch.storage.storageClassName }}
            storageClassName: {{ .Values.observability.elastic.elasticsearch.storage.storageClassName | quote }}
            {{- end }}
  podDisruptionBudget: {}
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.observability.elastic.kibana.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudops-kind-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: logs-ui
spec:
  version: {{ .Values.observability.elastic.version | quote }}
  image: {{ include "cloudops-kind-platform.image" .Values.observability.elastic.kibana.image | quote }}
  count: 1
  elasticsearchRef:
    name: {{ .Values.observability.elastic.elasticsearch.name }}
  http:
    service:
      spec:
        type: ClusterIP
  podTemplate:
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kibana
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.observability.elastic.kibana.resources | nindent 12 }}
{{- end }}
