groups:
  - name: custom_alerts
    rules:
      - alert: "TestHighCPU"
        expr: "sm_cpu_usage_percent > 80"
        for: "2m"
        labels:
          severity: "warning"
        annotations:
          summary: ""
          description: ""
