-- +goose Up
-- +goose NO TRANSACTION

CREATE TABLE `query_definitions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `definition_key` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `revision_number` bigint unsigned NOT NULL,
  `configuration_revision_id` bigint unsigned NOT NULL,
  `provider` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `mode` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `catalog_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `title` varchar(128) NOT NULL,
  `description` varchar(512) NOT NULL DEFAULT '',
  `query_text` text NOT NULL,
  `query_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `cluster_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `environment` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `namespaces_json` json NOT NULL,
  `resource_id` varchar(512) NOT NULL,
  `resource_kind` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `resource_namespace` varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `resource_name` varchar(253) NOT NULL,
  `max_lookback_seconds` int unsigned NOT NULL,
  `max_series` int unsigned NOT NULL,
  `max_samples` int unsigned NOT NULL,
  `content_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_by` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_query_definitions_public_id` (`public_id`),
  UNIQUE KEY `uk_query_definitions_revision` (`definition_key`,`revision_number`),
  UNIQUE KEY `uk_query_definitions_content` (`definition_key`,`content_hash`),
  KEY `idx_query_definitions_created` (`created_at`,`id`),
  KEY `idx_query_definitions_scope` (`cluster_id`,`resource_namespace`,`resource_name`,`created_at`),
  CONSTRAINT `fk_query_definitions_configuration_revision` FOREIGN KEY (`configuration_revision_id`) REFERENCES `configuration_revisions` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_query_definitions_identity` CHECK ((`revision_number` > 0 AND char_length(`query_hash`) = 64 AND char_length(`content_hash`) = 64)),
  CONSTRAINT `chk_query_definitions_mode` CHECK ((`mode` in (_ascii'guided',_ascii'expert'))),
  CONSTRAINT `chk_query_definitions_provider` CHECK ((`provider` = _ascii'prometheus')),
  CONSTRAINT `chk_query_definitions_bounds` CHECK ((`max_lookback_seconds` > 0 AND `max_series` > 0 AND `max_samples` > 0)),
  CONSTRAINT `chk_query_definitions_namespaces` CHECK ((json_type(`namespaces_json`) = _utf8mb4'ARRAY' AND json_length(`namespaces_json`) between 1 and 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `query_authorizations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `authorization_mode` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `configuration_revision_id` bigint unsigned NOT NULL,
  `query_definition_id` bigint unsigned DEFAULT NULL,
  `provider` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `query_mode` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `catalog_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `exact_query_text` text NOT NULL,
  `exact_query_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `cluster_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `environment` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `namespaces_json` json NOT NULL,
  `resource_id` varchar(512) NOT NULL,
  `resource_kind` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `resource_namespace` varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `resource_name` varchar(253) NOT NULL,
  `max_lookback_seconds` int unsigned NOT NULL,
  `max_series` int unsigned NOT NULL,
  `max_samples` int unsigned NOT NULL,
  `consumed_execution_public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `revoked_by` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `created_by` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_query_authorizations_public_id` (`public_id`),
  KEY `idx_query_authorizations_definition` (`query_definition_id`,`revoked_at`,`created_at`),
  KEY `idx_query_authorizations_scope` (`cluster_id`,`resource_namespace`,`resource_name`,`revoked_at`),
  CONSTRAINT `fk_query_authorizations_configuration_revision` FOREIGN KEY (`configuration_revision_id`) REFERENCES `configuration_revisions` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_query_authorizations_definition` FOREIGN KEY (`query_definition_id`) REFERENCES `query_definitions` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_query_authorizations_mode` CHECK (((`authorization_mode` = _ascii'run_once' AND `query_definition_id` is null) OR (`authorization_mode` = _ascii'definition' AND `query_definition_id` is not null))),
  CONSTRAINT `chk_query_authorizations_provider` CHECK ((`provider` = _ascii'prometheus')),
  CONSTRAINT `chk_query_authorizations_query_mode` CHECK ((`query_mode` in (_ascii'guided',_ascii'expert'))),
  CONSTRAINT `chk_query_authorizations_hash` CHECK ((char_length(`exact_query_hash`) = 64)),
  CONSTRAINT `chk_query_authorizations_bounds` CHECK ((`max_lookback_seconds` > 0 AND `max_series` > 0 AND `max_samples` > 0)),
  CONSTRAINT `chk_query_authorizations_namespaces` CHECK ((json_type(`namespaces_json`) = _utf8mb4'ARRAY' AND json_length(`namespaces_json`) between 1 and 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `query_executions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `configuration_revision_id` bigint unsigned NOT NULL,
  `query_definition_id` bigint unsigned DEFAULT NULL,
  `query_authorization_id` bigint unsigned DEFAULT NULL,
  `actor` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `provider` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `mode` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `catalog_key` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `query_text` text NOT NULL,
  `query_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `cluster_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `environment` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `namespaces_json` json NOT NULL,
  `resource_id` varchar(512) NOT NULL,
  `resource_kind` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `resource_namespace` varchar(253) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `resource_name` varchar(253) NOT NULL,
  `range_start` datetime(6) NOT NULL,
  `range_end` datetime(6) NOT NULL,
  `step_seconds` int unsigned NOT NULL,
  `timeout_ms` int unsigned NOT NULL,
  `max_response_bytes` int unsigned NOT NULL,
  `max_series` int unsigned NOT NULL,
  `max_samples` int unsigned NOT NULL,
  `concurrency_limit` int unsigned NOT NULL,
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `provider_identity` varchar(512) NOT NULL DEFAULT '',
  `provider_server_version` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `provider_collected_at` datetime(6) DEFAULT NULL,
  `result_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `series_count` int unsigned NOT NULL DEFAULT '0',
  `sample_count` int unsigned NOT NULL DEFAULT '0',
  `response_bytes` int unsigned NOT NULL DEFAULT '0',
  `partial` tinyint(1) NOT NULL DEFAULT '0',
  `truncated` tinyint(1) NOT NULL DEFAULT '0',
  `error_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `error_detail` varchar(512) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `started_at` datetime(6) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_query_executions_public_id` (`public_id`),
  KEY `idx_query_executions_history` (`created_at`,`id`),
  KEY `idx_query_executions_scope` (`cluster_id`,`resource_namespace`,`resource_name`,`created_at`),
  KEY `idx_query_executions_status` (`status`,`created_at`,`id`),
  CONSTRAINT `fk_query_executions_configuration_revision` FOREIGN KEY (`configuration_revision_id`) REFERENCES `configuration_revisions` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_query_executions_definition` FOREIGN KEY (`query_definition_id`) REFERENCES `query_definitions` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_query_executions_authorization` FOREIGN KEY (`query_authorization_id`) REFERENCES `query_authorizations` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_query_executions_actor` CHECK ((`actor` in (_ascii'owner',_ascii'agent'))),
  CONSTRAINT `chk_query_executions_provider` CHECK ((`provider` = _ascii'prometheus')),
  CONSTRAINT `chk_query_executions_mode` CHECK ((`mode` in (_ascii'guided',_ascii'expert'))),
  CONSTRAINT `chk_query_executions_status` CHECK ((`status` in (_ascii'pending',_ascii'running',_ascii'succeeded',_ascii'failed',_ascii'cancelled'))),
  CONSTRAINT `chk_query_executions_range` CHECK ((`range_end` > `range_start` AND `step_seconds` > 0)),
  CONSTRAINT `chk_query_executions_bounds` CHECK ((`timeout_ms` > 0 AND `max_response_bytes` > 0 AND `max_series` > 0 AND `max_samples` > 0 AND `concurrency_limit` > 0)),
  CONSTRAINT `chk_query_executions_hash` CHECK ((char_length(`query_hash`) = 64)),
  CONSTRAINT `chk_query_executions_namespaces` CHECK ((json_type(`namespaces_json`) = _utf8mb4'ARRAY' AND json_length(`namespaces_json`) between 1 and 100)),
  CONSTRAINT `chk_query_executions_terminal` CHECK (((`status` in (_ascii'pending',_ascii'running') AND `completed_at` is null) OR (`status` in (_ascii'succeeded',_ascii'failed',_ascii'cancelled') AND `completed_at` is not null)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `query_execution_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `public_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `query_execution_id` bigint unsigned NOT NULL,
  `sequence` int unsigned NOT NULL,
  `event_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `actor` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `detail` varchar(512) NOT NULL DEFAULT '',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_query_execution_events_public_id` (`public_id`),
  UNIQUE KEY `uk_query_execution_events_sequence` (`query_execution_id`,`sequence`),
  KEY `idx_query_execution_events_created` (`created_at`,`id`),
  CONSTRAINT `fk_query_execution_events_execution` FOREIGN KEY (`query_execution_id`) REFERENCES `query_executions` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `chk_query_execution_events_sequence` CHECK ((`sequence` > 0)),
  CONSTRAINT `chk_query_execution_events_actor` CHECK ((`actor` in (_ascii'owner',_ascii'agent',_ascii'system'))),
  CONSTRAINT `chk_query_execution_events_type` CHECK ((`event_type` in (_ascii'created',_ascii'started',_ascii'succeeded',_ascii'failed',_ascii'cancel_requested',_ascii'cancelled')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
