image:
  repository: mysql
  tag: 8.0.46
  digest: sha256:7dcddc01f13bab2f15cde676d44d01f61fc9f99fe7785e86196dfc07d358ae2b
  pullPolicy: IfNotPresent
database:
  name: cloudops
  user: cloudops
  secretName: cloudops-v3-database
  passwordKey: MYSQL_PASSWORD
  rootPasswordKey: MYSQL_ROOT_PASSWORD
persistence:
  size: 2Gi
  storageClassName: ""
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
