defaultRules:
  create: false
grafana:
  enabled: false
kubeStateMetrics:
  enabled: false
kube-state-metrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus-node-exporter:
  enabled: false

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 1m
    route:
      group_by: [alertname, namespace, service]
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 4h
      receiver: "null"
      routes:
        - receiver: cloudops-v3-webhook
          matchers:
            - signal_target="cloudops-demo"
    receivers:
      - name: "null"
      - name: cloudops-v3-webhook
        webhook_configs:
          - url: http://cloudops-api-internal.cloudops-system.svc:8082/webhooks/alertmanager
            send_resolved: true
            max_alerts: 0
            http_config:
              authorization:
                type: Bearer
                credentials_file: /etc/alertmanager/secrets/cloudops-alertmanager-webhook/token
  alertmanagerSpec:
    replicas: 1
    retention: 2h
    automountServiceAccountToken: false
    secrets:
      - cloudops-alertmanager-webhook
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 2h
    enableAdminAPI: false
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        cloudops.io/monitoring: enabled
    serviceMonitorNamespaceSelector:
      matchLabels:
        cloudops.io/monitoring: enabled
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector:
      matchLabels:
        cloudops.io/monitoring: enabled
    podMonitorNamespaceSelector:
      matchLabels:
        cloudops.io/monitoring: enabled
    ruleSelectorNilUsesHelmValues: false
    ruleSelector:
      matchLabels:
        cloudops.io/monitoring: enabled
    ruleNamespaceSelector:
      matchLabels:
        cloudops.io/monitoring: enabled
    probeSelectorNilUsesHelmValues: false
    probeSelector:
      matchLabels:
        cloudops.io/monitoring: enabled
    probeNamespaceSelector:
      matchLabels:
        cloudops.io/monitoring: enabled
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 750m
        memory: 1Gi

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tls:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi
