import type { RouteRecordRaw } from "vue-router";

export const appRoutes: RouteRecordRaw[] = [
  { path: "/login", name: "login", component: () => import("../pages/LoginPage.vue"), meta: { public: true, title: "登录", hidden: true } },
  { path: "/", redirect: "/incidents", meta: { title: "Incident Workbench", hidden: true } },
  { path: "/incidents", name: "incidents", component: () => import("../views/incidents/IncidentListView.vue"), meta: { title: "Incident Workbench", icon: "FirstAidKit", group: "incident" } },
  { path: "/incidents/:incidentId", name: "incident-detail", component: () => import("../views/incidents/IncidentDetailView.vue"), meta: { title: "Incident Detail", hidden: true } },
  { path: "/overview", name: "overview", component: () => import("../pages/OverviewPage.vue"), meta: { title: "总览（Legacy）", icon: "Monitor", group: "legacy", legacy: true } },
  { path: "/hosts", name: "hosts", component: () => import("../pages/HostsPage.vue"), meta: { title: "主机", icon: "Monitor", group: "monitor" } },
  { path: "/hosts/:instance", name: "host-detail", component: () => import("../pages/HostDetailPage.vue"), props: true, meta: { title: "主机详情", hidden: true } },
  { path: "/status", name: "status", component: () => import("../pages/StatusPage.vue"), meta: { title: "状态", icon: "CircleCheck", group: "monitor" } },
  { path: "/alerts", name: "alerts", component: () => import("../pages/AlertsPage.vue"), meta: { title: "当前告警（Legacy）", icon: "Bell", group: "alert", legacy: true } },
  { path: "/alert-histories", name: "alert-histories", component: () => import("../pages/AlertHistoriesPage.vue"), meta: { title: "历史告警", icon: "Clock", group: "alert", legacy: true } },
  { path: "/copilot", name: "copilot", component: () => import("../pages/CopilotPage.vue"), meta: { title: "Copilot（Legacy）", icon: "ChatDotRound", group: "ai", fullBleed: true, legacy: true } },
  { path: "/diagnosis", name: "diagnosis", component: () => import("../pages/DiagnosisListPage.vue"), meta: { title: "诊断（Legacy）", icon: "FirstAidKit", group: "ai", legacy: true } },
  { path: "/diagnosis/:id", name: "diagnosis-detail", component: () => import("../pages/DiagnosisDetailPage.vue"), props: true, meta: { title: "诊断详情", hidden: true, legacy: true } },
  { path: "/actions", name: "actions", component: () => import("../pages/ActionsPage.vue"), meta: { admin: true, title: "动作（Legacy）", icon: "Operation", group: "admin", legacy: true } },
  { path: "/actions/:id", name: "action-detail", component: () => import("../pages/ActionDetailPage.vue"), props: true, meta: { admin: true, title: "动作详情", hidden: true, legacy: true } },
  { path: "/audit-logs", name: "audit-logs", component: () => import("../pages/AuditLogsPage.vue"), meta: { admin: true, title: "审计日志（Legacy）", icon: "Document", group: "admin", legacy: true } },
  { path: "/settings", name: "settings", component: () => import("../pages/SettingsPage.vue"), meta: { admin: true, title: "设置", icon: "Setting", group: "settings" } },
  { path: "/settings/alert-rules", name: "settings-alert-rules", component: () => import("../pages/AlertRulesPage.vue"), meta: { admin: true, title: "告警规则", icon: "AlarmClock", group: "settings" } },
  { path: "/settings/channels", name: "settings-channels", component: () => import("../pages/ChannelsPage.vue"), meta: { admin: true, title: "通知渠道", icon: "Message", group: "settings" } },
  { path: "/settings/users", name: "settings-users", component: () => import("../pages/UsersPage.vue"), meta: { admin: true, title: "用户管理", icon: "User", group: "settings" } },
  { path: "/k8s", name: "k8s-overview", component: () => import("../pages/K8sOverviewPage.vue"), meta: { title: "集群概览", icon: "Grid", group: "k8s", legacy: true } },
  { path: "/k8s/nodes", name: "k8s-nodes", component: () => import("../pages/K8sNodesPage.vue"), meta: { title: "Nodes", icon: "Monitor", group: "k8s", nodesRequired: true, legacy: true } },
  { path: "/k8s/nodes/:name", name: "k8s-node-detail", component: () => import("../pages/K8sNodeDetailPage.vue"), props: true, meta: { title: "Node 详情", icon: "Monitor", group: "k8s", hidden: true, nodesRequired: true, legacy: true } },
  { path: "/k8s/workloads", name: "k8s-workloads", component: () => import("../pages/K8sWorkloadsPage.vue"), meta: { title: "Workloads", icon: "Box", group: "k8s", legacy: true } },
  { path: "/k8s/services", name: "k8s-services", component: () => import("../pages/K8sServicesPage.vue"), meta: { title: "Services", icon: "Connection", group: "k8s", legacy: true } },
  { path: "/k8s/events", name: "k8s-events", component: () => import("../pages/K8sEventsPage.vue"), meta: { title: "Events", icon: "Bell", group: "k8s", legacy: true } },
  { path: "/k8s/configmaps", name: "k8s-configmaps", component: () => import("../pages/K8sConfigMapsPage.vue"), meta: { title: "ConfigMaps", icon: "Document", group: "k8s", legacy: true } },
  { path: "/k8s/ingresses", name: "k8s-ingresses", component: () => import("../pages/K8sIngressesPage.vue"), meta: { title: "Ingress", icon: "Guide", group: "k8s", legacy: true } },
  { path: "/k8s/storage", name: "k8s-storage", component: () => import("../pages/K8sStoragePage.vue"), meta: { title: "Storage", icon: "Coin", group: "k8s", legacy: true } },
  { path: "/k8s/quotas", name: "k8s-quotas", component: () => import("../pages/K8sQuotasPage.vue"), meta: { title: "Quotas", icon: "DataLine", group: "k8s", legacy: true } },
  { path: "/k8s/hpas", name: "k8s-hpas", component: () => import("../pages/K8sHPAPage.vue"), meta: { title: "HPA", icon: "Odometer", group: "k8s", legacy: true } },
  { path: "/k8s/topology", name: "k8s-topology", component: () => import("../pages/K8sTopologyPage.vue"), meta: { title: "拓扑图", icon: "Share", group: "k8s", legacy: true } },
  { path: "/:pathMatch(.*)*", name: "not-found", component: () => import("../pages/NotFoundPage.vue"), meta: { title: "404", hidden: true } },
];
