apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudops-demo
  namespace: cloudops-argocd
spec:
  description: CloudOps V3 demo GitOps boundary
  sourceRepos:
    - https://github.com/05allan1213/cloudops-gitops-demo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: demo
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: monitoring.coreos.com
      kind: PodMonitor
    - group: monitoring.coreos.com
      kind: PrometheusRule
